@startuml
skinparam BoxPadding 20
skinparam ParticipantPadding 10
'https://plantuml.com/sequence-diagram

title "=Admin Uploading New Role Play Content\n"

actor Admin order 05
box "Verasana"
	participant App order 10
	participant Server order 15
	participant Database order 20
end box

box "Google Cloud Platform"
	participant Trigger order 30
	participant "Storage Bucket" as Storage order 35
end box

Admin --> App: Submits info \nfor Role Play content
App <-- Server: Returns signed URL
App --> Storage: Uploads role play
Trigger <-- Storage: Receives trigger \n new asset created
Server <-- Trigger: Sends new storage \nbucket asset event
Server --> Database: Adds new record to \nMux table
Server --> Database: Adds new record to \nContent table
Server --> Database: Adds new Role Play \ncontent ID to module's \nlist of contents
Admin --> App: Proceeds to \n next step
@enduml
