@startuml
skinparam BoxPadding 20
skinparam ParticipantPadding 10
'https://plantuml.com/sequence-diagram

title "=Learner Uploading Role Play Reply\n"

actor Learner order 05
box "Verasana"
	participant App order 10
	participant Server order 15
	participant Database order 20
end box

box "Google Cloud Platform"
	participant Trigger order 30
	participant "Storage Bucket" as Storage order 35
end box

Learner --> App: Submits info \nfor role play reply
App <-- Server: Returns signed URL
App --> Storage: Uploads video
Trigger <-- Storage: Receives trigger \n new asset created
Server <-- Trigger: Sends new storage \nbucket asset event
Server --> Database: Adds new record to \n Mux table
Server --> Database: Adds new record to \n progress table
Server --> Database: Adds new record to \n review table
Learner --> App: Proceeds to \nnext step and \nwaits for review
@enduml
