@startuml
'https://plantuml.com/class-diagram
!include entities/user.puml
!include entities/learning_group.puml
!include entities/program/program.puml
!include entities/program/module.puml
!include entities/program/content.puml

skinparam roundcorner 12


LearningGroup::managers "N" -- "M" User::id
LearningGroup::programs "N" -- "M" Program::id
' also many for this one but already have M label
' for User::id
LearningGroup::learners "N" -- User::id
Program::id "M" -- "N" Module::id
Module::id "M" -- "N" Content::id

hide methods
@enduml